package db

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jcsvwinston/nucleus/pkg/observe"
)

// liveSchemaDriftTable is the per-dialect DDL the live SchemaDrift
// tests provision before exercising the comparator. Mirrors the shape
// of the AutoMigrate live test model (id PK, email NOT NULL, nickname
// nullable, created_at NOT NULL) so the two surfaces stay in sync.
const liveSchemaDriftTableName = "ci_schemadrift_live_users"

// liveSchemaDriftDDL renders the CREATE TABLE for the test fixture in
// the dialect of the supplied DB.System(). Oracle and MSSQL diverge
// non-trivially from the ANSI-style SQLite/PG/MySQL form, so each
// engine gets its own literal — this keeps the test independent of the
// AutoMigrate scaffolder (whose own behaviour is exercised separately
// in pkg/app/automigrate_live_test.go).
func liveSchemaDriftDDL(system string) string {
	switch system {
	case "postgresql":
		return fmt.Sprintf(`CREATE TABLE %s (
			id BIGSERIAL PRIMARY KEY,
			email TEXT NOT NULL,
			nickname TEXT,
			created_at TIMESTAMPTZ NOT NULL
		)`, liveSchemaDriftTableName)
	case "mysql":
		return fmt.Sprintf("CREATE TABLE `%s` ("+
			"`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"+
			"`email` TEXT NOT NULL,"+
			"`nickname` TEXT,"+
			"`created_at` DATETIME NOT NULL"+
			")", liveSchemaDriftTableName)
	case "mssql":
		// SQL Server: NVARCHAR for free-form text (TEXT is deprecated);
		// IDENTITY for auto-increment; brackets for identifiers.
		return fmt.Sprintf(`IF OBJECT_ID('%[1]s', 'U') IS NULL
		CREATE TABLE [%[1]s] (
			[id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
			[email] NVARCHAR(255) NOT NULL,
			[nickname] NVARCHAR(255) NULL,
			[created_at] DATETIME2 NOT NULL
		)`, liveSchemaDriftTableName)
	case "oracle":
		// Oracle: VARCHAR2 for text, identity column via 12c+ GENERATED
		// AS IDENTITY; double-quote the identifiers so the AutoMigrate
		// scaffolder's lower_snake_case names round-trip. Wrap in a
		// PL/SQL ORA-00955 swallow so re-runs don't ERROR-out.
		return fmt.Sprintf(`BEGIN
			EXECUTE IMMEDIATE 'CREATE TABLE "%[1]s" (
				"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				"email" VARCHAR2(255) NOT NULL,
				"nickname" VARCHAR2(255),
				"created_at" TIMESTAMP NOT NULL
			)';
		EXCEPTION
			WHEN OTHERS THEN
				IF SQLCODE != -955 THEN RAISE; END IF;
		END;`, liveSchemaDriftTableName)
	default:
		return ""
	}
}

func liveSchemaDriftDropDDL(system string) string {
	switch system {
	case "mssql":
		return fmt.Sprintf("IF OBJECT_ID('%[1]s', 'U') IS NOT NULL DROP TABLE [%[1]s]", liveSchemaDriftTableName)
	case "oracle":
		return fmt.Sprintf(`BEGIN
			EXECUTE IMMEDIATE 'DROP TABLE "%[1]s"';
		EXCEPTION
			WHEN OTHERS THEN
				IF SQLCODE != -942 THEN RAISE; END IF;
		END;`, liveSchemaDriftTableName)
	case "mysql":
		return fmt.Sprintf("DROP TABLE IF EXISTS `%s`", liveSchemaDriftTableName)
	default:
		return fmt.Sprintf(`DROP TABLE IF EXISTS "%s"`, liveSchemaDriftTableName)
	}
}

// TestSQLMatrix_SchemaDrift exercises Migrator.SchemaDrift end-to-end
// against the live Postgres or MySQL container brought up by the
// db-matrix-required CI lane. It creates a known fixture table,
// then asserts the four drift kinds the comparator emits — empty when
// the expected schema matches, schema_extra_column when the expected
// set omits a live column, schema_missing_column when the expected
// set adds one, schema_column_nullability when polarity differs.
//
// Skipped when NUCLEUS_SQL_MATRIX_URL is unset (local fast lane) or
// points at a non-required profile.
func TestSQLMatrix_SchemaDrift(t *testing.T) {
	rawURL := strings.TrimSpace(os.Getenv("NUCLEUS_SQL_MATRIX_URL"))
	if rawURL == "" {
		t.Skip("NUCLEUS_SQL_MATRIX_URL is not set; skipping SQL matrix SchemaDrift test")
	}
	lower := strings.ToLower(rawURL)
	isPG := strings.HasPrefix(lower, "postgres://") || strings.HasPrefix(lower, "postgresql://")
	isMySQL := strings.HasPrefix(lower, "mysql://")
	if !isPG && !isMySQL {
		t.Skipf("NUCLEUS_SQL_MATRIX_URL=%q is not a required SQL matrix profile", rawURL)
	}
	runSchemaDriftLive(t, rawURL)
}

// TestSQLMatrix_SchemaDrift_Exploratory is the MSSQL/Oracle counterpart
// to TestSQLMatrix_SchemaDrift. The exploratory CI lanes carry the
// mssql and oracle build tags respectively; the test is always
// compiled but skips when the env var is unset.
//
// This iteration (ADR-009 addendum) closed the
// ErrSchemaDriftUnsupported sentinel paths for MSSQL and Oracle; the
// live test is the verification.
func TestSQLMatrix_SchemaDrift_Exploratory(t *testing.T) {
	rawURL := strings.TrimSpace(os.Getenv("NUCLEUS_SQL_EXPLORATORY_URL"))
	if rawURL == "" {
		t.Skip("NUCLEUS_SQL_EXPLORATORY_URL is not set; skipping exploratory SchemaDrift test")
	}
	lower := strings.ToLower(rawURL)
	isMSSQL := strings.HasPrefix(lower, "sqlserver://") || strings.HasPrefix(lower, "mssql://")
	isOracle := strings.HasPrefix(lower, "oracle://")
	if !isMSSQL && !isOracle {
		t.Skipf("NUCLEUS_SQL_EXPLORATORY_URL=%q is not an MSSQL/Oracle exploratory profile", rawURL)
	}
	runSchemaDriftLive(t, rawURL)
}

// runSchemaDriftLive is the shared body for both required and
// exploratory live SchemaDrift tests.
func runSchemaDriftLive(t *testing.T, rawURL string) {
	t.Helper()

	logger := observe.NewLogger("error", "text")
	database, err := New(Config{
		Engine:      EngineSQL,
		DatabaseURL: rawURL,
	}, logger)
	if err != nil {
		t.Fatalf("db.New failed for live URL %q: %v", rawURL, err)
	}
	t.Cleanup(func() { _ = database.Close() })

	if err := database.Health(context.Background()); err != nil {
		t.Fatalf("db.Health failed for live URL %q: %v", rawURL, err)
	}

	sqlDB, err := database.SqlDB()
	if err != nil {
		t.Fatalf("db.SqlDB failed: %v", err)
	}
	system := database.System()

	// Defensive pre-clean: a flaky teardown from a previous run could
	// leave the table behind. Drop before re-creating. Drop again on
	// test exit so the next invocation starts clean.
	if dropStmt := liveSchemaDriftDropDDL(system); dropStmt != "" {
		_, _ = sqlDB.Exec(dropStmt)
	}
	t.Cleanup(func() {
		if dropStmt := liveSchemaDriftDropDDL(system); dropStmt != "" {
			_, _ = sqlDB.Exec(dropStmt)
		}
	})

	ddl := liveSchemaDriftDDL(system)
	if ddl == "" {
		t.Fatalf("no liveSchemaDriftDDL defined for system %q", system)
	}
	if _, err := sqlDB.Exec(ddl); err != nil {
		t.Fatalf("create fixture table on %s: %v", system, err)
	}

	migrator := NewMigrator(database, t.TempDir(), logger)
	ctx := context.Background()

	matchingExpected := []ExpectedTable{
		{
			Name: liveSchemaDriftTableName,
			Columns: []ExpectedColumn{
				{Name: "id", Nullable: false},
				{Name: "email", Nullable: false},
				{Name: "nickname", Nullable: true},
				{Name: "created_at", Nullable: false},
			},
		},
	}

	t.Run("matches", func(t *testing.T) {
		drift, err := migrator.SchemaDrift(ctx, matchingExpected)
		if err != nil {
			t.Fatalf("SchemaDrift: %v", err)
		}
		if len(drift) != 0 {
			t.Fatalf("expected zero drift when expected matches live, got %+v", drift)
		}
	})

	t.Run("missing_column", func(t *testing.T) {
		// Expected declares a column the live DB does not have.
		expected := append([]ExpectedTable{}, matchingExpected...)
		expected[0].Columns = append(expected[0].Columns,
			ExpectedColumn{Name: "ghost_column", Nullable: true})
		drift, err := migrator.SchemaDrift(ctx, expected)
		if err != nil {
			t.Fatalf("SchemaDrift: %v", err)
		}
		if !containsDrift(drift, DriftKindSchemaMissingColumn, liveSchemaDriftTableName, "ghost_column") {
			t.Fatalf("expected schema_missing_column for ghost_column, got %+v", drift)
		}
	})

	t.Run("extra_column", func(t *testing.T) {
		// Expected omits a column the live DB has.
		expected := []ExpectedTable{
			{
				Name: liveSchemaDriftTableName,
				Columns: []ExpectedColumn{
					{Name: "id", Nullable: false},
					{Name: "email", Nullable: false},
					{Name: "created_at", Nullable: false},
					// nickname intentionally omitted
				},
			},
		}
		drift, err := migrator.SchemaDrift(ctx, expected)
		if err != nil {
			t.Fatalf("SchemaDrift: %v", err)
		}
		if !containsDrift(drift, DriftKindSchemaExtraColumn, liveSchemaDriftTableName, "nickname") {
			t.Fatalf("expected schema_extra_column for nickname, got %+v", drift)
		}
	})

	t.Run("nullability_mismatch", func(t *testing.T) {
		// Expected claims email is nullable; live DB has it NOT NULL.
		expected := []ExpectedTable{
			{
				Name: liveSchemaDriftTableName,
				Columns: []ExpectedColumn{
					{Name: "id", Nullable: false},
					{Name: "email", Nullable: true},
					{Name: "nickname", Nullable: true},
					{Name: "created_at", Nullable: false},
				},
			},
		}
		drift, err := migrator.SchemaDrift(ctx, expected)
		if err != nil {
			t.Fatalf("SchemaDrift: %v", err)
		}
		entry, ok := findDrift(drift, DriftKindSchemaColumnNullability, liveSchemaDriftTableName, "email")
		if !ok {
			t.Fatalf("expected schema_column_nullability for email, got %+v", drift)
		}
		// Expected was nullable; actual is not_null.
		if entry.Expected != "nullable" || entry.Actual != "not_null" {
			t.Fatalf("unexpected nullability polarity: expected=%q actual=%q", entry.Expected, entry.Actual)
		}
	})

	t.Run("missing_table", func(t *testing.T) {
		// Expected names a second table the live DB doesn't have.
		expected := append([]ExpectedTable{}, matchingExpected...)
		expected = append(expected, ExpectedTable{
			Name: "ci_schemadrift_live_phantom",
			Columns: []ExpectedColumn{
				{Name: "id", Nullable: false},
			},
		})
		drift, err := migrator.SchemaDrift(ctx, expected)
		if err != nil {
			t.Fatalf("SchemaDrift: %v", err)
		}
		if !containsDrift(drift, DriftKindSchemaMissingTable, "ci_schemadrift_live_phantom", "") {
			t.Fatalf("expected schema_missing_table for ci_schemadrift_live_phantom, got %+v", drift)
		}
	})
}

func containsDrift(entries []SchemaDriftEntry, kind, table, column string) bool {
	_, ok := findDrift(entries, kind, table, column)
	return ok
}

func findDrift(entries []SchemaDriftEntry, kind, table, column string) (SchemaDriftEntry, bool) {
	for _, e := range entries {
		if e.Kind == kind && e.Table == table && e.Column == column {
			return e, true
		}
	}
	return SchemaDriftEntry{}, false
}

// Silence unused-import warnings for builds that never run the live
// tests (build tags such as mssql/oracle gate the driver registration
// but not this file). `time` is intentionally imported so a future
// extension that needs timestamps does not have to re-add it.
var _ time.Time
var _ *sql.DB
