// Code generated by Quark CLI. DO NOT EDIT.
package models

type StressRecords struct {
	ID int64 `db:"id" pk:"true" json:"id"`
	Data *string `db:"data" json:"data"`
	Value *int64 `db:"value" json:"value"`
}

func (StressRecords) TableName() string {
	return "stress_records"
}
