// Code generated by Quark CLI. DO NOT EDIT.
package models

type TestUsers struct {
	ID int64 `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (TestUsers) TableName() string {
	return "test_users"
}
