package cli

import (
	"fmt"
	"os"
	"path/filepath"
)

const contractsAggregatorTemplate = `package contracts

import "github.com/jcsvwinston/GoFrame/pkg/openapi"

type Registrar func(doc *openapi.Document)

type Config struct {
	Title       string
	Version     string
	Description string
	Servers     []openapi.Server
}

var registrars []Registrar

func RegisterContract(register Registrar) {
	if register == nil {
		return
	}
	registrars = append(registrars, register)
}

func Register(doc *openapi.Document) {
	if doc == nil {
		return
	}
	for _, register := range registrars {
		register(doc)
	}
}

func DefaultConfig() Config {
	return Config{
		Title:       %q,
		Version:     "0.1.0",
		Description: "Experimental OpenAPI contract generated by GoFrame from internal/contracts.",
		Servers: []openapi.Server{
			{URL: "/"},
		},
	}
}

func NewDocument() *openapi.Document {
	return NewDocumentWithConfig(DefaultConfig())
}

func NewDocumentWithConfig(cfg Config) *openapi.Document {
	if cfg.Title == "" {
		cfg.Title = DefaultConfig().Title
	}
	if cfg.Version == "" {
		cfg.Version = DefaultConfig().Version
	}
	doc := openapi.NewDocument(cfg.Title, cfg.Version)
	doc.Info.Description = cfg.Description
	if len(cfg.Servers) > 0 {
		doc.Servers = append([]openapi.Server(nil), cfg.Servers...)
	}
	Register(doc)
	return doc
}
`

func ensureContractsAggregator(outDir, title string) error {
	path := filepath.Join(outDir, "internal", "contracts", "contracts.go")
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("stat contracts aggregator: %w", err)
	}

	if title == "" {
		title = "Application API"
	}

	body := fmt.Sprintf(contractsAggregatorTemplate, title)
	return writeFileIfNotExists(path, body, false)
}

func defaultOpenAPITitle(projectName, modulePath, outDir string) string {
	if projectName = filepath.Base(projectName); projectName != "" && projectName != "." {
		return projectName + " API"
	}
	if modulePath != "" {
		return toPascalCase(filepath.Base(modulePath)) + " API"
	}
	if outDir != "" {
		base := filepath.Base(filepath.Clean(outDir))
		if base != "" && base != "." && base != string(filepath.Separator) {
			return toPascalCase(base) + " API"
		}
	}
	return "Application API"
}
