package models

import "github.com/jcsvwinston/GoFrame/pkg/model"

// Comment is a scaffold generated by goframe CLI.
type Comment struct {
	model.BaseModel

	Name string `db:"column:name;required;index" validate:"required" admin:"list,search"`
}
