package storage

import (
	"context"
	"fmt"
	"io"
	"mime"
	"os"
	"path/filepath"
	"time"
)

// LocalStore implements Store using the local filesystem.
// Suitable ONLY for development. Do NOT use in production.
type LocalStore struct {
	root string
}

// NewLocalStore creates a local filesystem storage backend.
func NewLocalStore(cfg LocalConfig) (*LocalStore, error) {
	root := cfg.Path
	if root == "" {
		root = "storage/"
	}

	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("storage: resolve local path %q: %w", root, err)
	}

	if err := os.MkdirAll(abs, 0755); err != nil {
		return nil, fmt.Errorf("storage: create local storage dir %q: %w", abs, err)
	}

	return &LocalStore{root: abs}, nil
}

func (s *LocalStore) fullPath(key string) string {
	return filepath.Join(s.root, filepath.FromSlash(key))
}

func (s *LocalStore) Put(ctx context.Context, key string, reader io.Reader, opts PutOptions) (ObjectInfo, error) {
	key = normalizeKey(key)
	if err := validateKey(key); err != nil {
		return ObjectInfo{}, err
	}

	path := s.fullPath(key)

	// Create parent directories
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Put mkdir %q: %w", filepath.Dir(path), err)
	}

	file, err := os.Create(path)
	if err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Put create %q: %w", key, err)
	}

	written, err := io.Copy(file, reader)
	if err != nil {
		file.Close()
		return ObjectInfo{}, fmt.Errorf("storage: local Put write %q: %w", key, err)
	}
	file.Close()

	info, _ := os.Stat(path)
	contentType := opts.ContentType
	if contentType == "" {
		contentType = mime.TypeByExtension(filepath.Ext(key))
	}
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	return ObjectInfo{
		Key:         key,
		Size:        written,
		ContentType: contentType,
		Visibility:  opts.Visibility,
		Metadata:    opts.Metadata,
		UpdatedAt:   info.ModTime(),
	}, nil
}

func (s *LocalStore) Get(ctx context.Context, key string) (io.ReadCloser, ObjectInfo, error) {
	key = normalizeKey(key)
	path := s.fullPath(key)

	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ObjectInfo{}, ErrNotFound(key)
		}
		return nil, ObjectInfo{}, fmt.Errorf("storage: local Get stat %q: %w", key, err)
	}

	file, err := os.Open(path)
	if err != nil {
		return nil, ObjectInfo{}, fmt.Errorf("storage: local Get open %q: %w", key, err)
	}

	contentType := mime.TypeByExtension(filepath.Ext(key))
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	return file, ObjectInfo{
		Key:         key,
		Size:        info.Size(),
		ContentType: contentType,
		Visibility:  Private,
		UpdatedAt:   info.ModTime(),
	}, nil
}

func (s *LocalStore) Delete(ctx context.Context, key string) error {
	key = normalizeKey(key)
	path := s.fullPath(key)

	err := os.Remove(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("storage: local Delete %q: %w", key, err)
	}
	return nil
}

func (s *LocalStore) Exists(ctx context.Context, key string) (bool, error) {
	key = normalizeKey(key)
	path := s.fullPath(key)

	_, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("storage: local Exists %q: %w", key, err)
	}
	return true, nil
}

func (s *LocalStore) List(ctx context.Context, opts ListOptions) (ListResult, error) {
	prefix := normalizeKey(opts.Prefix)
	searchPath := s.fullPath(prefix)

	entries, err := os.ReadDir(searchPath)
	if err != nil {
		if os.IsNotExist(err) {
			return ListResult{}, nil
		}
		return ListResult{}, fmt.Errorf("storage: local List %q: %w", prefix, err)
	}

	result := ListResult{}
	for _, entry := range entries {
		info, err := entry.Info()
		if err != nil {
			continue
		}
		key := prefix + entry.Name()
		if entry.IsDir() && opts.Delimiter != "" {
			result.CommonPrefixes = append(result.CommonPrefixes, key+"/")
			continue
		}
		if len(result.Objects) >= opts.Limit && opts.Limit > 0 {
			result.Truncated = true
			break
		}
		result.Objects = append(result.Objects, ObjectInfo{
			Key:       key,
			Size:      info.Size(),
			UpdatedAt: info.ModTime(),
		})
	}

	return result, nil
}

func (s *LocalStore) PublicURL(ctx context.Context, key string, opts URLConfig) (string, error) {
	// Local store doesn't support public URLs natively.
	// URLs are generated by the app layer (see pkg/storage/public.go).
	return "", nil
}

func (s *LocalStore) SignedURL(ctx context.Context, key string, expires time.Duration, opts URLConfig) (string, error) {
	// Local store doesn't support signed URLs.
	// In development, the app serves files directly.
	return "", fmt.Errorf("storage: local driver does not support signed URLs")
}

func (s *LocalStore) Copy(ctx context.Context, srcKey, dstKey string) (ObjectInfo, error) {
	srcKey = normalizeKey(srcKey)
	dstKey = normalizeKey(dstKey)

	srcPath := s.fullPath(srcKey)
	dstPath := s.fullPath(dstKey)

	if err := os.MkdirAll(filepath.Dir(dstPath), 0755); err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Copy mkdir %q: %w", filepath.Dir(dstPath), err)
	}

	src, err := os.Open(srcPath)
	if err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Copy open src %q: %w", srcKey, err)
	}
	defer src.Close()

	dst, err := os.Create(dstPath)
	if err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Copy create dst %q: %w", dstKey, err)
	}
	defer dst.Close()

	written, err := io.Copy(dst, src)
	if err != nil {
		return ObjectInfo{}, fmt.Errorf("storage: local Copy write %q: %w", dstKey, err)
	}

	info, _ := os.Stat(dstPath)
	return ObjectInfo{
		Key:       dstKey,
		Size:      written,
		UpdatedAt: info.ModTime(),
	}, nil
}

func (s *LocalStore) Close() error {
	return nil
}
