package admin

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/jcsvwinston/nucleus/pkg/auth"
)

// BootstrapAdminConfig defines how the framework should initialize the first
// admin account when the admin users table is empty.
type BootstrapAdminConfig struct {
	Username string
	Email    string
	Password string
}

// BootstrapAdminResult reports whether a bootstrap admin account was created.
// Password is only populated when generated by the framework.
type BootstrapAdminResult struct {
	Created           bool
	Username          string
	Password          string
	PasswordGenerated bool
}

// EnsureBootstrapAdminUser guarantees the admin users table exists and creates
// one default superuser if the table is currently empty.
func EnsureBootstrapAdminUser(ctx context.Context, sqlDB *sql.DB, cfg BootstrapAdminConfig) (BootstrapAdminResult, error) {
	if sqlDB == nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap: nil sql db")
	}
	if ctx == nil {
		ctx = context.Background()
	}

	username := strings.TrimSpace(cfg.Username)
	if username == "" {
		username = "admin"
	}
	email := strings.TrimSpace(cfg.Email)
	if email == "" {
		email = "admin@localhost"
	}
	password := strings.TrimSpace(cfg.Password)
	passwordGenerated := false
	if password == "" {
		password = newBootstrapAdminPassword()
		passwordGenerated = true
	}
	if len(password) < 8 {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap password must be at least 8 characters")
	}

	if err := ensureBootstrapAdminUsersTable(ctx, sqlDB); err != nil {
		return BootstrapAdminResult{}, err
	}

	count, err := countBootstrapAdminUsers(ctx, sqlDB)
	if err != nil {
		return BootstrapAdminResult{}, err
	}
	if count > 0 {
		return BootstrapAdminResult{
			Created:           false,
			Username:          username,
			PasswordGenerated: false,
		}, nil
	}

	hash, err := auth.HashPassword(password)
	if err != nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap hash password: %w", err)
	}

	userID := newBootstrapAdminUserID()
	now := time.Now().UTC().Format(time.RFC3339)
	insert := fmt.Sprintf(
		"INSERT INTO %s (id, username, email, password_hash, is_superuser, created_at, updated_at) VALUES (%s, %s, %s, %s, %d, %s, %s)",
		defaultAdminUsersTable,
		quoteBootstrapSQLString(userID),
		quoteBootstrapSQLString(username),
		quoteBootstrapSQLString(email),
		quoteBootstrapSQLString(hash),
		1,
		quoteBootstrapSQLString(now),
		quoteBootstrapSQLString(now),
	)
	if _, err := sqlDB.ExecContext(ctx, insert); err != nil {
		if isBootstrapDuplicateError(err) {
			return BootstrapAdminResult{
				Created:           false,
				Username:          username,
				PasswordGenerated: false,
			}, nil
		}
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap insert user: %w", err)
	}

	result := BootstrapAdminResult{
		Created:           true,
		Username:          username,
		PasswordGenerated: passwordGenerated,
	}
	if passwordGenerated {
		result.Password = password
	}
	return result, nil
}

func ensureBootstrapAdminUsersTable(ctx context.Context, sqlDB *sql.DB) error {
	query := fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id VARCHAR(64) PRIMARY KEY,
	username VARCHAR(191) NOT NULL UNIQUE,
	email VARCHAR(191) NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	is_superuser INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
)
`, defaultAdminUsersTable)
	if _, err := sqlDB.ExecContext(ctx, query); err != nil {
		return fmt.Errorf("admin bootstrap ensure users table: %w", err)
	}
	return nil
}

func countBootstrapAdminUsers(ctx context.Context, sqlDB *sql.DB) (int, error) {
	var count int
	query := fmt.Sprintf("SELECT COUNT(*) FROM %s", defaultAdminUsersTable)
	if err := sqlDB.QueryRowContext(ctx, query).Scan(&count); err != nil {
		return 0, fmt.Errorf("admin bootstrap count users: %w", err)
	}
	return count, nil
}

func newBootstrapAdminPassword() string {
	buf := make([]byte, 14)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("goframe-%d", time.Now().UnixNano())
	}
	return "goframe-" + hex.EncodeToString(buf)
}

func newBootstrapAdminUserID() string {
	buf := make([]byte, 6)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("u_%d", time.Now().UnixNano())
	}
	return "u_" + time.Now().UTC().Format("20060102150405") + "_" + hex.EncodeToString(buf)
}

func quoteBootstrapSQLString(raw string) string {
	return "'" + strings.ReplaceAll(raw, "'", "''") + "'"
}

func isBootstrapDuplicateError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	if strings.Contains(msg, "unique constraint") {
		return true
	}
	if strings.Contains(msg, "duplicate key") {
		return true
	}
	if strings.Contains(msg, "duplicate entry") {
		return true
	}
	if strings.Contains(msg, "violates unique") {
		return true
	}
	return false
}
