// Code generated by Quark CLI. DO NOT EDIT.
package models

type CacheModels struct {
	ID int `db:"id" pk:"true" json:"id"`
	Data *string `db:"data" json:"data"`
}

func (CacheModels) TableName() string {
	return "cache_models"
}
