// Code generated by Quark CLI. DO NOT EDIT.
package models

type JsonDocs struct {
	ID int `db:"id" pk:"true" json:"id"`
	Metadata *string `db:"metadata" json:"metadata"`
}

func (JsonDocs) TableName() string {
	return "json_docs"
}
