// Code generated by Quark CLI. DO NOT EDIT.
package models

type RAuthors struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (RAuthors) TableName() string {
	return "r_authors"
}
