// Code generated by Quark CLI. DO NOT EDIT.
package models

type RPosts struct {
	ID int `db:"id" pk:"true" json:"id"`
	Title *string `db:"title" json:"title"`
	AuthorID *int `db:"author_id" json:"author_id"`
}

func (RPosts) TableName() string {
	return "r_posts"
}
