// Code generated by Quark CLI. DO NOT EDIT.
package models

type RProfiles struct {
	ID int `db:"id" pk:"true" json:"id"`
	Bio *string `db:"bio" json:"bio"`
	AuthorID *int `db:"author_id" json:"author_id"`
}

func (RProfiles) TableName() string {
	return "r_profiles"
}
