// Code generated by Quark CLI. DO NOT EDIT.
package models

type SyncUsers struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (SyncUsers) TableName() string {
	return "sync_users"
}
